name: Deploy to Server

on:
  push:
    branches:
      - main # 当 main 分支有 push 时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }} # 服务器 IP
        username: ${{ secrets.SERVER_USERNAME }} # 服务器用户名
        key: ${{ secrets.SSH_PRIVATE_KEY }} # SSH 私钥
        script: |
          cd /var/www/jiyibi-app
          git pull origin main
          npm install
          npm run build
          pm2 restart jiyibi-api
